import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import Sidebar from "@/components/dashboard/Sidebar";
import Header from "@/components/dashboard/Header";
import MobileMenu from "@/components/dashboard/MobileMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Minty Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <body className={`${inter.className} flex fixed inset-0 overflow-auto`}>
            <div className="w-[17%] h-screen"> 
                <Sidebar />
            </div>
            <div className="w-full px-5 py-4 lg:px-20 lg:py-10">
                <MobileMenu />
                <Header />
                {children}
            </div>    
          </body>
        </html>
      );
}
