import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import Sidebar from "@/components/dashboard/Sidebar";
import Header from "@/components/dashboard/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Minty Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <body className={`${inter.className} flex justify-start fixed inset-0 overflow-auto`}>
            <div className="w-[17%] h-screen"> 
                <Sidebar />
            </div>
            <div className="w-full px-20 py-10">
                <Header />
                {children}
            </div>    
          </body>
        </html>
      );
}
